# Generated by Django 2.2 on 2020-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_restapi', '0002_auto_20200624_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
